backend:
  name: github
  repo: jameshd/gatsby-demo
  branch: main

media_folder: "content/assets"

collections:
  - name: blog
    label: Blog Posts
    folder: "content/blog/"
    create: true
    slug: "{{title}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
