backend:
  name: github
  repo: jameshd/gatsby-demo
  branch: main

media_folder: "content/assets"

collections:
  - name: blog
    label: Blog Post
    folder: "content/blog"
    path: "{{title}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    summary: "{{title}}:  {{date}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "MMM Do YY" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
